cacheFolder: .yarn/cache

compressionLevel: 0

checksumBehavior: ignore # necessary on Windows because of https://github.com/yarnpkg/berry/issues/5795

enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-4.9.1.cjs

packageExtensions:
  react@*:
    peerDependencies:
      react: "*"
  react-dom@*:
    peerDependencies:
      react-dom: "*"
